#!/bin/bash
set -e
. /usr/lib/qubes/init/functions
[ `id -u` -eq 0 ] || exit 1
[ -e qubes-tunnel.service ] || exit 1
if is_rwonly_persistent; then
    echo "Error: Please run installer in a template or standalone VM."
    exit 1
fi

echo "Starting qubes-tunnel install..."

groupadd -rf qtunnel
tunfiles="qtunnel-setup qtunnel-connect tunnel-restrict-firewall"
svc="qubes-tunnel.service"
chown -R root:root $tunfiles $svc $svc.d
chmod +x $tunfiles
cp -a $tunfiles   -t /usr/lib/qubes
cp -a $svc $svc.d -t /lib/systemd/system
sync; sleep 2s; systemctl daemon-reload
systemctl enable $svc

if is_templatevm; then
    echo "Almost done..."
    echo "Next, shutdown this template then start proxyVM and run:"
    echo "sudo /usr/lib/qubes/qtunnel-setup --config"
elif is_fully_persistent; then
    /usr/lib/qubes/qtunnel-setup --config
fi
