#!/bin/bash
export PATH="$PATH:/usr/sbin:/sbin:/bin"
[ `id -u` -eq 0 ] || exit 1
. /usr/lib/qubes/init/functions

qtunpath=/rw/config/qtunnel
uppath=$qtunpath/tunneluserpwd.txt
tmppath="/tmp/"`basename $uppath`

do_userpass () {
    echo
    read -p  "VPN/tunnel username: " username
    read -s -p "VPN/tunnel password: " upassword
    echo
    echo
    echo "$username" >$tmppath.tmp
    echo "$upassword" >>$tmppath.tmp
    chmod 600 $tmppath.tmp
    mv $tmppath.tmp $tmppath
    cp -a $tmppath $uppath
    echo -e "\nLogin info saved to $uppath"
    sleep 1s
    echo
}

# needs source dir passed as first arg
firewall_link () {
    if iptables -L QBS-FORWARD >/dev/null; then
    # firewall for Qubes 4
        mkdir -p /rw/config/qubes-firewall.d
        ln -s -f $1/tunnel-restrict-firewall \
    /rw/config/qubes-firewall.d/90_tunnel-restrict
    else
        ln -s -f $1/tunnel-restrict-firewall \
    /rw/config/qubes-firewall-user-script
    fi
}


case "$1" in
--install-DELETE-ME!)

    if [ ! -d qtunnel ]; then exit 1; fi
    chown -R root:root *
    chmod +x rc.local qtunnel-ns qtunnel-setup proxy-firewall-restrict

    if is_templatevm ; then
        echo "Install into templateVM..."
        groupadd -rf qtunnel
        cp -a qubes-tunnel.service* /lib/systemd/system
        sync; sleep 2s; systemctl daemon-reload
        systemctl enable qubes-tunnel.service
        cp -a qtunnel-ns qtunnel-setup proxy-firewall-restrict \
    -t /usr/lib/qubes
        echo "Almost done..."
        echo "Next, shutdown this template then start proxyVM and run:"
        echo "sudo /usr/lib/qubes/qtunnel-setup --config"

    elif is_proxyvm ; then
        echo -n "Isolated install for proxyVM..."
        cp -a qtunnel rc.local qubes-tunnel.service* qtunnel-setup \
    qtunnel-ns proxy-firewall-restrict -t /rw/config
        ln -s -f /rw/config/proxy-firewall-restrict \
    /rw/config/qubes-firewall-user-script
        echo "copy complete."
        do_userpass
        echo "Done!"

    else
        echo "No appropriate VM type; Exiting."
        exit 1
    fi
;;

--config)
    if is_proxyvm ; then
        mkdir -p $qtunpath
        firewall_link /usr/lib/qubes
        do_userpass
        echo "Done!"
        if [ ! -e $qtunpath/qtunnel.conf ]; then
            echo "Next, copy or link your config file to $qtunpath/qtunnel.conf"
        fi
    else
        echo "Error: Not a proxyVM. Please check instructions."
        exit 1
    fi
;;

--pre-start)
    if [ ! -f $uppath ]; then
        if [ ! -f /tmp/qtunnel-askpass ]; then
            systemd-run --unit=qtunnel-askpass -E DISPLAY=:0 sh -c \
            'sleep 2s; /usr/bin/xterm \
            -T "Tunnel Login" -e /usr/lib/qubes/qtunnel-setup --xterm'
        fi
    else
        cp -a $uppath $tmppath.tmp
        mv $tmppath.tmp $tmppath
    fi
;;

--xterm)
    touch /tmp/qtunnel-askpass
    do_userpass
;;
esac

