#!/bin/bash

###########################################################################
##  qtunnel-connect
##
## Handles DHCP-source DNS addresses & link notification for Qubes VPN VMs.
## To use, set as 'up' and 'down' script with parameter in your tunnel config.
##
## Use 'tunnel_dns' environment var as override/alternative.
## In openvpn config, format is: setenv tunnel_dns 'X.X.X.X  Y.Y.Y.Y [...]'

set -e
export PATH="$PATH:/usr/sbin:/sbin:/bin"
nspath=/var/run/qubes/qubes-tunnel-ns

case "$1" in
up)
    iptables -t nat -F PR-QBS
    if [[ -z "$tunnel_dns" ]] ; then
        # Parses DHCP option variables to set DNS address translation:
        for optionname in ${!foreign_option_*} ; do
            option="${!optionname}"
            unset fops; fops=($option)
            if [ ${fops[1]} == "DNS" ] ; then tunnel_dns="$tunnel_dns ${fops[2]}" ; fi
        done
    fi
    if [[ -n "$tunnel_dns" ]] ; then
        # Set DNS address translation in firewall:
        echo "$tunnel_dns " >$nspath
        echo "Using DNS servers $tunnel_dns"
        # Securely restart firewall (Qubes ver <4 only)
        iptables -L QBS-FORWARD || systemctl restart qubes-firewall
        . /var/run/qubes/qubes-ns
        q_addr=$NS1
        for DNS in $tunnel_dns; do
            iptables -t nat -A PR-QBS -d $q_addr -i vif+ -p udp --dport 53 -j DNAT --to $DNS
            iptables -t nat -A PR-QBS -d $q_addr -i vif+ -p tcp --dport 53 -j DNAT --to $DNS
            q_addr=$NS2
        done

        su - -c 'notify-send "$(hostname): LINK IS UP." --icon=network-idle' user
    else
        su - -c 'notify-send "$(hostname): LINK UP, NO DNS!" --icon=dialog-error' user
    fi

    ;;
down)
    iptables -t nat -F PR-QBS
    su - -c 'notify-send "$(hostname): LINK IS DOWN !" --icon=dialog-error' user

    ;;
esac
