#!/bin/sh
export PATH="$PATH:/usr/sbin:/sbin:/bin"
[ `id -u` -eq 0 ] || exit 1

qtunpath=/rw/config/qtunnel
upfile=tunneluserpwd.txt
tmppath=/tmp/$upfile

do_userpass () {
    bash /usr/lib/qubes/qtunnel-setup --userpass-bash
}

# Need bash for password prompt
do_userpass_bash () {
    echo
    read -p  "VPN/tunnel username: " username
    read -s -p "VPN/tunnel password: " upassword
    echo
    echo
    echo "$username" >$tmppath.tmp
    echo "$upassword" >>$tmppath.tmp
    chmod 600 $tmppath.tmp
    mv $tmppath.tmp $tmppath
    cp -a $tmppath $qtunpath/$upfile
    echo -e "\nLogin info saved to $qtunpath/$upfile"
    sleep 1s
    echo
}

# needs source dir passed as first arg
firewall_link () {
    if iptables -L QBS-FORWARD >/dev/null; then
    # firewall for Qubes 4
        mkdir -p /rw/config/qubes-firewall.d
        ln -s -f $1/tunnel-restrict-firewall \
    /rw/config/qubes-firewall.d/90_tunnel-restrict
    else
        ln -s -f -b $1/tunnel-restrict-firewall \
    /rw/config/qubes-firewall-user-script
    fi
}


case "$1" in

--pre-start)
# Check for login file and prompt if necessary.
    if [ ! -f $qtunpath/$upfile ]; then
        if [ ! -f /tmp/qtunnel-askpass ]; then
            systemd-run --unit=qtunnel-askpass -E DISPLAY=:0 sh -c \
            'sleep 2s; /usr/bin/xterm \
            -T "Tunnel Login" -e /usr/lib/qubes/qtunnel-setup --xterm'
        fi
    elif [ ! -f $tmppath ]; then
        cp -a $qtunpath/$upfile $tmppath.tmp
        mv $tmppath.tmp $tmppath
        if [ -e /var/run/qubes-service/vpn-handler-openvpn ]; then
            # workaround for openvpn option parser bug:
            # process config to override options.
            grep -Ev '^[[:space:]]*(up|down|script-security|keepalive)[[:space:]]+' \
              $qtunpath/qtunnel.conf  >/tmp/qtunnel.conf
        else
            cp -aL $qtunpath/qtunnel.conf /tmp
        fi
        sync
	su - -c 'notify-send "$(hostname): Ready to start link."' user
    fi
;;

--post-start)
    echo "START-ing network forwarding!"
    echo '1' > /proc/sys/net/ipv4/ip_forward
# '0' appears to be default setting for ipv6
#    echo '1' > /proc/sys/net/ipv6/conf/all/forwarding
;;

--check-firewall)
    for i in 1 2 3; do
        if iptables -C FORWARD -o eth0 -j DROP \
        && iptables -C FORWARD -i eth0 -j DROP ; then
            exit 0
        elif [ $i = 3 ]; then
            echo "Error: Firewall rule(s) not enabled!"
            exit 1
        fi
        sleep 2s
    done
;;

--post-stop)
    echo "STOP-ing network forwarding!"
    echo '0' > /proc/sys/net/ipv4/ip_forward
    echo '0' > /proc/sys/net/ipv6/conf/all/forwarding
;;

--config)
    . /usr/lib/qubes/init/functions
    if is_proxyvm ; then
        mkdir -p $qtunpath
        firewall_link /usr/lib/qubes
        do_userpass
        echo "Done!"
        if [ ! -e $qtunpath/qtunnel.conf ]; then
            echo "Next, copy or link your config file to $qtunpath/qtunnel.conf"
        fi
    else
        echo "Error: Not a proxyVM. Please check instructions."
        exit 1
    fi
;;

--config-nm)
    . /usr/lib/qubes/init/functions
    if is_proxyvm ; then
        firewall_link /usr/lib/qubes
        echo "Done!"
    else
        echo "Error: Not a proxyVM. Please check instructions."
        exit 1
    fi
;;

--xterm)
    touch /tmp/qtunnel-askpass
    do_userpass
;;

--userpass-bash)
    do_userpass_bash
;;

--version)
    echo "1.4.0"
;;

esac

